### ISSUE TITLE
"Fyne shopping list" is damaged and can't be opened

### ISSUE THREAD

**Issue by kennethchoe** [Bluebugs/shopping#12]
My environment:
Apple M1 Pro 2021
OSX 12.6.5

I downloaded the zip file from https://geoffrey-artefacts.fynelabs.com/github/Bluebugs/Bluebugs/shopping/latest/index.html for Apple M1/2, and when I run the unzipped file, I get this error:
<img width="260" alt="image" src="https://github.com/Bluebugs/shopping/assets/1812592/552a072d-0e65-4390-85a0-194aa7f1bffb">

Is there anything I could check?
This might be due to my company laptop having too strict policy, so please let me know if it works on any OSX machine (with which version it worked with).

**Comment by Bluebugs** [comment]
The m1 and m2 require either the binary to be signed or the tag on the file to indicate it can be trusted. I forgot the command for that and will try to find it again. And I have not gotten yet an apple certificate to sign the binary.

**Comment by Bluebugs** [comment]
You can compile the binary your self using fyne directly as that would give it the right tag.

**Comment by Bluebugs** [comment]
Would you mind trying the direction from https://github.com/Jacalz/rymdport#running-on-macos-arm64-m1m2 . If it work I will add that to the README.

**Comment by kennethchoe** [comment]
That worked!
